name: kh_calendar
description: "A beautiful custom calendar widget with full Khmer language support including Khmer numerals, month names, and day names. Built with pure Flutter without external dependencies."
version: 0.0.1
homepage: https://github.com/KUNVATH/kh_calendar.git
repository: https://github.com/KUNVATH/kh_calendar.git

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

topics:
  - calendar
  - khmer
  - cambodia
  - localization
  - widget
